### ISSUE TITLE
Yugioh Standard style is broken: collection has no member 'language'

### ISSUE THREAD

**Issue by iconmaster5326** [MagicSetEditorPacks/Full-Non-Magic-Pack#1]
When I try to create a card using the Yugioh Standard style, the console lights up with various error messages of the usual form:

```
collection has no member 'language'
  in function is_en
  in function get_sep
  while updating card value 'monster_type'
```

This prevents me from filling in most fields on the card.

**Comment by CajunAvenger** [comment]
ye whoever did the yugioh frames for some reason game-level coded a style option, gonna get that sorted out here soon
